Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnsanK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class İnsanKaynaklarıEntities : DbContext
    {
        public İnsanKaynaklarıEntities()
            : base("name=İnsanKaynaklarıEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGörev> tblGörev { get; set; }
        public virtual DbSet<TblPersonel> TblPersonel { get; set; }
    }
}

Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\İsmailPc\Source\Repos\İnsanKaynakları\İnsanK\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Models/TblPersonel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnsanK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public int Personelİd { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string Telno { get; set; }
        public string Tcno { get; set; }
        public int Görev { get; set; }
    
        public virtual tblGörev tblGörev { get; set; }
    }
}

Models/tblGörev.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnsanK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGörev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGörev()
        {
            this.TblPersonel = new HashSet<TblPersonel>();
        }
    
        public int GörevİD { get; set; }
        public string Görevadı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPersonel> TblPersonel { get; set; }
    }
}

Controllers/GorevController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using İnsanK.Models;
namespace İnsanK.Controllers
{

    public class GorevController : Controller
    {
        İnsanKaynaklarıEntities db = new İnsanKaynaklarıEntities();
        // GET: Gorev
        public ActionResult Index2()
        {
            var gorevler = db.tblGörev.ToList();
            return View(gorevler);
        }
        [HttpGet]
        public ActionResult GorevEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GorevEkle(tblGörev g)
        {
            db.tblGörev.Add(g);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
        public ActionResult GorevSil(int id)
        {
            var gorev = db.tblGörev.Find(id);
            db.tblGörev.Remove(gorev);
            _=db.SaveChanges();
            return RedirectToAction("Index2");
        }
        public ActionResult GorevGetir(int id)
        {
            var grv = db.tblGörev.Find(id);
            return View("GorevGetir", grv);
        }
        public ActionResult GorevGuncelle(tblGörev g)
        {
            var grv = db.tblGörev.Find(g.GörevİD);
            grv.GörevİD = g.GörevİD;
            grv.Görevadı = g.Görevadı;            
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
    }
}

Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using İnsanK.Models;

namespace İnsanK.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        İnsanKaynaklarıEntities db = new İnsanKaynaklarıEntities();
        public ActionResult Index()
        {
            var personeller = db.TblPersonel.ToList();
            return View(personeller);
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(TblPersonel p)
        {
            db.TblPersonel.Add(p);
           _ = db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelSil(int id)
        {
            var personel = db.TblPersonel.Find(id);
            db.TblPersonel.Remove(personel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetir(int id)
        {
            var per = db.TblPersonel.Find(id);
            return View("PersonelGetir" , per);
        }
        public ActionResult PersonelGuncelle(TblPersonel p)
        {
            var person = db.TblPersonel.Find(p.Personelİd);
            person.Adı = p.Adı;
            person.Soyadı = p.Soyadı;
            person.Tcno = p.Tcno;
            person.Telno = p.Telno;
            person.Görev = p.Görev;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Gorev/GorevEkle.cshtml
@model İnsanK.Models.tblGörev
@{
    ViewBag.Title = "GorevEkle";
    Layout = "~/Views/Shared/_PersonelLayout.cshtml";
}

@using (Html.BeginForm("GorevEkle", "Gorev", FormMethod.Post))
{
    <h2>GorevEkle</h2>
    <br />

    <form class="form-group" metod="post">
        <div style="margin-bottom:15px">
            
            @Html.LabelFor(x => x.GörevİD)
            @Html.TextBoxFor(x => x.GörevİD, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            @Html.LabelFor(x => x.Görevadı)
            @Html.TextBoxFor(x => x.Görevadı, new { @class = "form-control" })
        </div>

        <button class="btn btn-info">Kaydet</button>
    </form>
}

Views/Gorev/GorevGetir.cshtml
@model İnsanK.Models.tblGörev
@{
    ViewBag.Title = "GorevGetir";
    Layout = "~/Views/Shared/_PersonelLayout.cshtml";
}

@using (Html.BeginForm("GorevGuncelle", "Gorev", FormMethod.Post))
{
    <div style="margin-bottom:15px">
        @Html.HiddenFor(y => y.GörevİD)
        @Html.LabelFor(x => x.GörevİD)
        @Html.TextBoxFor(x => x.GörevİD, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Görevadı)
        @Html.TextBoxFor(x => x.Görevadı, new { @class = "form-control" })
    </div>
    <button class="btn btn-success">Güncelle</button>
}

Views/Gorev/Index2.cshtml
@using İnsanK.Models;
@model List<tblGörev>
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_PersonelLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Görevi</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

@foreach (var item in Model)
{
<tr>
    <td>@item.GörevİD</td>
    <td>@item.Görevadı</td>
    <td><a href="/Gorev/GorevSil/@item.GörevİD" class="btn btn-warning">Sil</a></td>
    <td><a href="/Gorev/GorevGetir/@item.GörevİD" class="btn btn-warning">Güncelle</a></td>
</tr>
}
</table>
<a href="/Gorev/GorevEkle/" class="btn btn-warning">Yeni Görev</a>

Views/Personel/Index.cshtml
@using İnsanK.Models;
@model List<TblPersonel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PersonelLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Adı</th>
        <th>Soyadı</th>
        <th>Tc no</th>
        <th>Tel no</th>
        <th>görevi</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Personelİd</td>
            <td>@item.Adı</td>
            <td>@item.Soyadı</td>   
            <td>@item.Tcno</td>
            <td>@item.Telno</td>          
            <td>@item.tblGörev.Görevadı</td>
            <td><a href="/Personel/PersonelSil/@item.Personelİd" class="btn btn-danger">Sil</a></td>
            <td><a href="/Personel/PersonelGetir/@item.Personelİd" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>
  <a href="/Personel/PersonelEkle"class="btn btn-warning">Yeni Personel</a>

Views/Personel/PersonelEkle.cshtml
@model İnsanK.Models.TblPersonel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/_PersonelLayout.cshtml";
}
@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post))
{
    <h2>PersonelEkle</h2>
<br />

<form class="form-group" metod="post">
    <div style="margin-bottom:15px">
        @Html.HiddenFor(y => y.Personelİd)
        @Html.LabelFor(x => x.Adı)
        @Html.TextBoxFor(x => x.Adı, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Soyadı)
        @Html.TextBoxFor(x => x.Soyadı, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Tcno)
        @Html.TextBoxFor(x => x.Tcno, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Telno)
        @Html.TextBoxFor(x => x.Telno, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Görev)
        @Html.TextBoxFor(x => x.Görev, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Kaydet</button>
</form>
}

Views/Personel/PersonelGetir.cshtml
@model İnsanK.Models.TblPersonel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/_PersonelLayout.cshtml";
}

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
    <div style="margin-bottom:15px">
        @Html.HiddenFor(y=>y.Personelİd)
        @Html.LabelFor(x => x.Adı)
        @Html.TextBoxFor(x => x.Adı, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Soyadı)
        @Html.TextBoxFor(x => x.Soyadı, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Tcno)
        @Html.TextBoxFor(x => x.Tcno, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Telno)
        @Html.TextBoxFor(x => x.Telno, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        @Html.LabelFor(x => x.Görev)
        @Html.TextBoxFor(x => x.Görev, new { @class = "form-control" })
    </div>
    <button class="btn btn-success">Güncelle</button>
}

Views/Shared/_PersonelLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">İnsan Kaynaları</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="/Personel/Index/">Personeller</a></li>
                <li><a href="/Gorev/Index2/">Görev</a></li>
                <li><a href="#">Yardım</a></li>
              
            </ul>
        </div>
    </nav>

    <div class="container">
       @RenderBody()
    </div>

</body>
</html>